import { test, expect } from "@playwright/test";
import { syntheticUser, passwordLogin, enroll, openAccounts } from "./helpers";

test("create, edit, archive, restore, delete an account and log out", async ({ page }, testInfo) => {
  const name = `Synthetic savings ${testInfo.project.name} ${Date.now()}`;
  const email = await syntheticUser();
  const status = await passwordLogin(page, email);
  if (status === "MFA_SETUP_REQUIRED") { await enroll(page); }
  await openAccounts(page);
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await page.getByLabel("Account name").fill(name);
  await page.getByLabel("Account type").selectOption("SAVINGS");
  await page.getByLabel("Currency", { exact: true }).fill("CHF");
  await page.getByLabel("Opening balance", { exact: true }).fill("1234.56");
  await page.getByLabel("Opening date").fill("2026-10-04");
  await page.getByRole("button", { name: "Save account", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  await page.reload();
  const account = page.getByRole("article").filter({ has: page.getByRole("heading", { name, exact: true }) });
  await expect(account).toContainText("CHF 1’234.56");
  await account.getByRole("button", { name, exact: true }).click();
  await expect(page.getByText(/^Opening balance:/)).toContainText("2026-10-04");
  await page.getByRole("button", { name: "Back to accounts" }).click();
  await account.getByRole("button", { name: "Edit", exact: true }).click();
  const changedName = `${name} updated`;
  await page.getByLabel("Account name").fill(changedName);
  await page.getByLabel("Opening balance", { exact: true }).fill("99999999999999999999.12345678");
  await page.getByRole("button", { name: "Save account", exact: true }).click();
  await expect(page.getByRole("heading", { name: changedName, exact: true })).toBeVisible();
  await page.reload();
  const changed = page.getByRole("article").filter({ has: page.getByRole("heading", { name: changedName, exact: true }) });
  await expect(changed).toContainText("CHF 99’999’999’999’999’999’999.12345678");
  await changed.getByRole("button", { name: "Archive", exact: true }).click();
  await expect(page.getByRole("heading", { name: changedName, exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Archived accounts" }).click();
  await expect(changed).toContainText("Archived");
  await page.reload();
  await page.getByRole("button", { name: "Archived accounts" }).click();
  await changed.getByRole("button", { name: "Restore", exact: true }).click();
  await expect(page.getByRole("heading", { name: "No archived accounts" })).toBeVisible();
  await page.getByRole("button", { name: "Active accounts" }).click();
  await expect(changed).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("accounts.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await changed.getByRole("button", { name: "Delete", exact: true }).click();
  await page.getByRole("button", { name: "Cancel deletion" }).click();
  await expect(changed).toBeVisible();
  await changed.getByRole("button", { name: "Delete", exact: true }).click();
  await page.getByRole("button", { name: "Confirm deletion" }).click();
  await expect(page.getByRole("heading", { name: "Your first account starts here" })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "Your first account starts here" })).toBeVisible();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Welcome back" })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "Welcome back" })).toBeVisible();
  expect((await page.request.get("/api/v1/accounts")).status()).toBe(401);
});
